### ISSUE TITLE
F1 2020

### ISSUE THREAD

**Issue by ItsOKayCZ** [SWAGRIDcz/f12019TrackGenerator#2]
There should be an option to select between F1 2019 and 2020.

**Comment by SWAGRIDcz** [comment]
OMG U SO GENIUS THX FOR IDEA!

**Comment by SWAGRIDcz** [comment]
Done

**Comment by ItsOKayCZ** [comment]
Test linked commit: 4f48ff701a0a678f2d305f37e83626238185a57e
